
We briefly explain the high school and college entrance exams in Taiwan for readers all over the world.^[<https://en.wikipedia.org/wiki/Education_in_Taiwan>] Like many other places in Asia, Taiwan used to put heavy emphasis on standardized tests in high school and college admissions \cite{chou2019taiwan}. This differs from the US college admission system,^[<https://www.usnews.com/education/best-colleges/articles/college-application-process>] which values more of students' overall qualifications such as extracurricular activities and personal qualities, not solely on a single standardized test score \cite{wechsler2017qualified, jeffrey2024unpacking}.   

Nowadays, Taiwan has added some non-exam components for middle and high school students,^[<http://www.ater.org.tw/journal/article/9-6/free/12.pdf>] in order to educate them to be well-rounded \cite{coudenys2022path}. Despite multiple attempts of education reform, the high school entrance exam in Taiwan remains a key part to high school admissions \cite{chen2017advancing, chen2008strategic}. The college admission process in Taiwan is a more complicated system \cite{liu2022pathways}. Although Taiwan's college admission process requires students to submit their portfolio as part of their application package,^[<https://tinyurl.com/mtp627ne>] students still need to score high enough in the college entrance exam to pass the initial screening round.^[<https://www.thenewslens.com/article/179752>]   


## High School Entrance Exam in Taiwan {#HighSchool_PR}  

Between 2001 and 2013, the high school entrance exam in Taiwan was officially called The Basic Competence Test for Junior High School Students \cite{chou2007schooling, sung2014standards}.^[Wikipedia link: <https://bit.ly/2JNQaOI>] The exam consisted of five subjects (Chinese, English, mathematics, physical sciences, and social sciences). Note that two exams was held each year in 2001-2011 \cite{huang2021effect}, and students could take one or both exams because the difficulty level was about equal.^[<https://www.epochtimes.com/b5/5/7/16/n987486.htm>] The first exam was during May-June and the second one was in July. Each student could use either set of score (typically the better one) to get their high school placement. The report card contains exam scores for each subject, the total score, and the percentile rank (PR values from 1 to 99) of the total score. The PR value refers to the percentage of the student population you scored higher than. For example, PR 86 means you have a higher score than 86% of the student population in Taiwan. The PR values serve as a normalized tool to compare academic achievements across years.   

While the PR values remained consistent, the actual exam score range varied across years. In 2001-2006, each of the five subjects had a maximum score of 60, summing up to a total score of 300. In Year 2007, the independent essay question was added for another 12 points, bringing up the maximum total score to 312 points.^[<https://tinyurl.com/2wrjk89a>] The scoring of the high school entrance exam had been controversial and generated much discussion in the news.^[<https://taiwan.chtsai.org/2007/06/23/guozhong_jice_hai_youjiu_ma/>] The main issue was the large score difference between full marks and getting only one question wrong in a test subject \cite{chang2006methods}. For instance, one could get a 60 with all questions correct in a subject, but only 55 by missing just one question. The five-point deduction was regarded as a harsh penalty, given that the knowledge difference was minimal between a perfect score and a near-perfect score.^[<https://www.parenting.com.tw/article/5020588>] Then in Year 2009, the maximum possible score was increased from 312 to 412 points.^[<https://blog.cybertranslator.idv.tw/archives/2384>] Each subject was augmented from 60 to 80 points, and the independent essay question was still worth 12 points. In the 80-point system, missing one question would result in a two-point loss from the full mark, rather than a substantial five or six points.^[<https://joan044.pixnet.net/blog/post/255140987>]      

In the later stages of this high school entrance exam format, subtle changes were made in 2011 and 2012, until the final year in 2013. The high school entrance exam had used the same questions across the whole country, but in Year 2011, Taipei and its surrounding areas created their own version of entrance exam.^[<https://web.fg.tp.edu.tw/~tispa/blog/epaper/01/word/d1-2-2.pdf>] The education officials claimed that more granularity was needed to distinguish students' academic ability in such competitive areas.^[<https://bit.ly/3Zq2c6e>] Then in Year 2012, the high school entrance exam was suddenly reduced to one exam per year instead of two,^[<https://www.grow22.com/subject/A002.pdf>] and this continued in Year 2013.^[<https://www.ettoday.net/news/20130609/220042.htm>] In 2012 and 2013, the "second exam" was replaced with a pre-exam admission process: Each middle school could submit formal recommendations for their students to high schools, with a limited quota per high school \cite{chen2010comparison}. Students who got admitted by a high school would not have to take the entrance exam.^[<https://news.ltn.com.tw/news/life/breakingnews/537370>] The controversy was that the changes were implemented quickly, so neither students nor teachers in middle schools were adequately prepared to make optimal choices.^[<https://www.nhu.edu.tw/~society/e-j/104/a40.htm>]    

A major reform came in Year 2014, and the high school entrance exam was officially replaced with the Comprehensive Assessment Program (CAP) for Junior High School Students \cite{huang2019high}.^[Wikipedia link: <https://bit.ly/41xYSrh>] Instead of using PR values that emphasized the ranking, CAP provides each student with seven letter grades for each subject (C, B, B+, B++, A, A+, A++) and an independent essay score (0-6).^[<https://www.parenting.com.tw/article/5049351>] Each region in Taiwan sets their own rules for high school admission decisions,^[<https://www.facebook.com/JayWangFB/posts/188393636138799/>] and the CAP score is a necessary but not sufficient condition to get into a top high school \cite{dur2022deduction}. For example, Taipei and its surrounding areas award points for completing five semesters of physical education, arts and humanities, and integrative activities (with an average grade of C or better).^[<https://se.ntpc.edu.tw/12basic/Main/Main1_2>] Tainan (southern part of Taiwan) also requires additional criteria such as physical fitness, volunteering activities, and participation in student organizations.^[<https://www.tainan.gov.tw/news_content.aspx?n=13371&s=3749018>]  

**Remark**: Since the data were self-reported in 2015, the high school entrance exam scores included only PR values and did not include any letter grades. In the CAP era starting in 2014, the wide variance of high school admission requirements makes it more difficult to compare across students' academic achievements \cite{chao2024high}.      

## College Entrance Exam in Taiwan {#College_Score}

The college entrance exams in Taiwan are held twice a year by the College Entrance Examination Center (CEEC).^[<https://www.ceec.edu.tw/>] The first exam is called the General Scholastic Ability Test (GSAT), and the scores are used for early admission. The second exam is called the Advanced Subjects Test (AST), and the scores are used for regular admission. The college admission rules in Taiwan are changed every several years, but the format of two entrance exams has been used for 20+ years and is here to stay \cite{chou2015higher, chiang2022exams}.  


### General Scholastic Ability Test (GSAT) {#College_GSAT} 

The GSAT has been in place since 1994, and the exam is typically held in late January or early February.^[<https://bit.ly/2W0fdUq>] Students can use the GSAT scores and additional criteria (i.e., their portfolio documents) to apply to colleges for early admission \cite{hsieh2019preliminary}. Starting in 2022, the early admission from GSAT is not as "early" anymore.^[<https://www.mediglobal.org/en/node/561>] The timeline of the first round of college admission has been postponed from March to May, leaving high school students little time to prepare for the upcoming second exam in July.^[<https://www.parenting.com.tw/article/5094739>]  

The GSAT consists of five subjects (Chinese, English, mathematics, physical sciences, and social sciences), each of which are graded on a 0 to 15 point scale. The GSAT scores are normalized to a range of 0 to 75, regardless of the difficulty level of GSAT each year. On the other hand, the scores of AST can vary widely because each subject is scored separately from 0 to 100. Since the AST scores fluctuate more due to the difficulty level of the exam questions each year, we decided to use the GSAT scores as a benchmark of the college exam scores.  

The 0 to 15 point scale is calculated in three steps:^[<https://bit.ly/3bxIuSn>]    

1. Compute the "top" as the average raw score of the highest 1% among test takers.
2. Divide the number by 15 to get the scale interval.
3. Create a table to map raw scores to the 0 to 15 point scale.  

For example, if a subject has the "top" of 93.45 (max 100), then the scale interval is 93.45/15 = 6.23, rounded to two decimal points. Zero point is reserved for absolute zero marks on the exam. A student will get 1 point for a raw score between 0.01 and 6.23, and 2 points for a raw score between 6.24 and 12.46, and so on. If we observe from the top of the scale, a student can get 15 points for a raw score between 87.23 and 100, and 14 points for a raw score between 81.00 and 87.22. Note that the threshold (87.23) to achieve 15 points is 14 times of the scale interval (6.23).   

The GSAT grows and changes over time, and the college admission system in Taiwan has become more complicated \cite{hou2021historical, yu2024benefits}.^[Wikipedia link: <http://tinyurl.com/3r5zrzhs>] Starting in 2019, high school students may choose four of the five subjects for the GSAT, while each subject is still scored on the 0-15 scale as before \cite{liu2023inside}. High school students are also required to maintain a portfolio each semester to document their learning outcomes \cite{chang2021academic}, and the portfolio will be evaluated by the colleges they apply to.^[<https://www.108epo.com/courses.php>] In 2022, the GSAT separated mathematics into two subjects -- mathematics A and mathematics B.^[<https://bit.ly/4bEoQ0y>] The other four subjects continues as before (Chinese, English, physical sciences, and social sciences). Each college and department can decide which GSAT subjects should be considered in their admission process. For example, some business majors require mathematics A, and some others require mathematics B.^[<https://www.taisounds.com/news/content/125/111292>]   


### Advanced Subjects Test (AST) {#College_AST}

The original AST existed from 2002 to 2021, and each subject was scored from 0 to 100 points. The  original AST was almost always held on July 1st, 2nd, and 3rd each year.^[<https://bit.ly/2J7YxoW>] In the regular admission phase, the AST scores were directly used for college placements \cite{shy2021comparison}. Some colleges had GSAT score requirements in addition to the AST scores.^[<https://www.epochtimes.com/b5/11/2/21/n3176290.htm>] There were ten subjects in the original AST: Chinese, English, mathematics A, mathematics B, physics, chemistry, biology, civics & social studies, geography, and history. Students may register for 3-10 subjects, depending on specific requirements of each college or department. The difficulty level of each AST subject varied across years, so the scores had a wide variance.^[<https://www.ettoday.net/news/20190702/1480531.htm>]     

In 2022, the original AST was replaced with the new AST with major changes, and each subjects was graded on a 0 to 60 point scale (rather than from 0 to 100 points).^[<https://www.ceec.edu.tw/unithome?psid=0J129606443348127072>] A key difference is that Chinese and English are removed from the new AST, and students are required to use the GSAT scores for these two subjects.^[<https://www.cw.com.tw/article/5119369>] In fact, the majority of colleges require both GSAT and AST scores even for the regular admission.^[<https://www2.uac.edu.tw/uac111_note/uacpdf/uac4135_113.pdf>] The dates were also changed to mid-July. During 2022-2024, there were seven subjects available in the AST: mathematics A, physics, chemistry, biology, civics & social studies, geography, and history.^[<https://bit.ly/4bx63Eh>] Then mathematics B will be added back to the AST starting in 2025.^[<http://tinyurl.com/ycvetzsd>] Since the new AST is fairly recent, parents and students in Taiwan are still adapting to the changes.^[<https://bit.ly/3QDh6E7>]   
