We would like to direct readers to resources for learning statistics and data science, in order to expand their professional skillsets. Online information is abundant and probably overwhelming, so we decided to categorize some examples based on difficulty level and the prerequisites. We also provide a brief description of each resource including goals and/or applications, so that readers can make informed decisions in choosing their own professional development activities. Section \ref{learning-statistics} points to some materials for learning statistics, while Section \ref{learning-data-science} takes a step forward to data science and programming.  

## Resources for Learning Statistics {#learning-statistics}

Statistics is the core of data analysis.^[<https://datascience.virginia.edu/news/how-much-do-data-scientists-need-know-about-statistics>] Even with the aid of machine learning algorithms and integrated computation tools, people still need to know the fundamental concepts in statistics to appropriately interpret the numbers from the data. For instance, when you take a sample from the population data, how do you verify that the sample is a representative sample? How do you interpret the model coefficients in the output? How do you ensure that all predictive probabilities are between zero and one? Integrated tools make it easy to build and run a model, but what's more important is to choose an appropriate model to implement for the project goal. We also need to be able to detect and troubleshoot issues in the model output.  

Here are some resources we recommend for the path of learning statistics, from introductory to advanced. Although some readers may be more interested in data science, learning statistics serves as a building block to becoming an expert data scientist. Human decisions also play a key role in getting useful insights from data,^[<https://ww2.amstat.org/meetings/sdss/2020/onlineprogram/AbstractDetails.cfm?AbstractID=308230>] and the statistical skills would help readers in making better decisions in data.   

The Statistics 101 course covers the fundamental statistical concepts for students to perform data analysis, and the programming component is often included. For readers who would like a refresher, we recommend the textbook *OpenIntro Statistics* \cite{diez2019openintro} and the online course series *Statistics with `R` Specialization* on Coursera.^[<https://www.coursera.org/specializations/statistics>] Basic concepts like hypothesis testing and confidence intervals are also asked in technical interviews for data science jobs. For an overview of Bayesian Statistics, we recommend the *Bayesian Statistics* online course on Coursera,^[<https://www.coursera.org/learn/bayesian>] along with the open-source textbook *An Introduction to Bayesian Thinking* \cite{clyde2018bayesian101}. At this stage, knowledge of calculus is helpful but not required.  
  
As the next step beyond the introductory level, we suggest reading *The Statistical Sleuth: A Course in Methods of Data Analysis* \cite{ramsey2013statistical}, which is the textbook for undergraduate-level regression analysis at Duke Statistical Science.^[<https://www2.stat.duke.edu/courses/Fall18/sta210.001/>] The book covers intermediate topics such as ANOVA (Analysis of Variance) and multiple linear regression. It also provides data files for case studies and exercises.^[<http://www.statisticalsleuth.com/>] *Statistics: Unlocking the Power of Data* \cite{lock2020statistics} is heavily focused on data analysis with real applications, and this textbook introduces computer simulation methods like bootstrap intervals and randomization tests for statistical inference. For a more theoretical overview of mathematical statistics, we recommend *Probability and Statistics* \cite{degroot2012probability} where calculus is a prerequisite. A solid theoretical background helps readers bridge the gap between writing code and understanding complex statistical models. When the readers go further in statistics, college-level mathematics becomes increasingly important. Formulas and equations will gradually appear in the curriculum, especially calculus for continuous functions and matrix algebra for discrete datapoints.  

For the advanced readers, we recommend the following graduate level statistics textbooks. Note that multivariate Calculus and matrix algebra are absolutely necessary at this stage. *A First Course in Bayesian Statistical Methods* \cite{hoff2009first} explains in detail on how to perform Bayesian statistical modeling, which is much more comprehensive than the Bayes' rule (conditional probability). For a focus on linear models, we suggest *A Modern Approach to Regression with `R`* \cite{sheather2009modern} with solid examples, especially on model validation and residual analysis. *Statistical Inference* \cite{casella2024statistical} is a must-read if you are interested in the theory behind statistical concepts such as maximum likelihood estimation. These textbooks build on statistical concepts that readers may have already learned at the beginner to intermediate levels. If we can recommend only one textbook, the one will be *Categorical Data Analysis* \cite{agresti2013categorical}. This book explains many generalized linear models in detail, such as logistic regression, Poisson log-linear model, and proportional hazards for survival analysis models. There are lots of categorical data in real life, making these models particularly useful.  

There are many other high-quality statistics textbooks in the universe, and we selected these as a starting point. If the readers are interested in a data science career, learning statistics builds the foundations and expands your toolbox to generate insights from data.^[<https://towardsdatascience.com/the-difference-between-data-science-and-statistics-168c7062c201>] We also recommend exploring Kaggle datasets^[<https://www.kaggle.com/datasets>] for hands-on practice. To get closer to analyzing real-world data, we encourage the readers to attend data hackathons, contribute to open-source projects, and/or volunteer technical skills at nonprofit organizations like Statistics Without Borders.^[<https://www.statisticswithoutborders.org/>] These activities are not a comprehensive list, and please feel free to get creative and carve your own professional path forward.    

## Resources for Data Science and Programming {#learning-data-science}

Since we discussed plenty of statistics resources in the previous section, we would like to provide a few pointers to **data science**, one of the hottest fields in tech.^[<https://www.linkedin.com/pulse/future-data-science-why-its-hottest-trend-tech-vladimir-ninov-mba/>] Programming is also essential to handle data, so we introduce some practical tools that readers can incorporate them into their data science workflow.   

This document is created with $\mathsf{R}$ Markdown \cite{r-markdown-pkg},^[<https://rmarkdown.rstudio.com/articles_intro.html>] which has a framework to directly incorporate code and graphs in the report. This not only reduces the errors from copy-pasting tables and plots, but also ensures reproducibility of the data analysis \cite{baumer2014r-markdown}. $\mathsf{R}$ Markdown can generate reports in PDF, HTML, or Microsoft Word formats. $\mathsf{R}$ Markdown also provides a template for presentation slides, and the output can be in PDF, HTML, or Microsoft PowerPoint files. Note that PDF output from $\mathsf{R}$ Markdown requires the installation of LaTeX.^[<https://bookdown.org/yihui/rmarkdown/pdf-document.html>] (An alternative way is to save the HTML output to a PDF, but this is a manual step outside the end-to-end pipeline.) For a full book with multiple chapters, we recommend using the $\mathsf{R}$ package `bookdown` \cite{r-bookdown} for a comprehensive and reproducible workflow.  

The graphs in this manuscript are mainly for demonstration; they are created using the basic `plot` function as the default in RStudio. For advanced data visualization, we highly encourage readers to use the $\mathsf{R}$ package `ggplot2` \cite{ggplot2}. This package provides much more capability to convey the message in a graph, and the foundations behind `ggplot2` are based on *The Grammar of Graphics* \cite{wilkinson2012grammar}. For a simple and hands-on guide for data visualization, we recommend the book *Visualize This* \cite{yau2024visualize} to determine which types of graphs are most appropriate for which scenarios. On the other hand, *Semiology of Graphics: Diagrams, Networks, Maps* \cite{bertin1983semiology} is a comprehensive textbook for data visualization theory. Concepts such as human perception are technology-agnostic; the principles apply to almost any tool for data visualization \cite{few2013data}.     

The $\mathsf{R}$ code is also for demonstration. The author makes every effort to ensure correctness and readability of the code, but errors and inconsistencies are inevitable. Since this is an open-source project on GitHub,^[<https://github.com/star1327p/Exam-Scores-PTT>] readers are welcome to make a pull request and/or report any issues. To learn more about better coding styles, we recommend the computer science books *Clean Code* \cite{martin2009clean} and *Code Complete* \cite{mcconnell2004code}. For complex operations in $\mathsf{R}$, we recommend the $\mathsf{R}$ package `tidyverse` \cite{r-tidyverse} because it provides a fast, efficient, and organized workflow for general data modeling.^[<https://www.r-bloggers.com/2018/09/why-learn-the-tidyverse/>] The book \textit{$\mathsf{R}$ for Data Science: Import, Tidy, Transform, Visualize, and Model Data} \cite{wickham2016r} demonstrates an end-to-end cycle of using `tidyverse` in data science.  

In addition to $\mathsf{R}$, Python is another commonly-used programming language in data science. Python is an object-oriented language which is closer to software development, while $\mathsf{R}$ is more focused on statistical models.^[<https://www.datacamp.com/tutorial/r-or-python-for-data-analysis>] Our suggestion is to learn both $\mathsf{R}$ and Python, so that the readers get to choose the one that fits their unique needs. (The author does not have a strong personal preference, so she often chooses the one that her collaborators use to better leverage their existing code.) After you know a programming language, it would not be difficult to learn a new one because many concepts are similar, such as `for` loops and user-defined functions. Don't worry!  

